# Generated by Django 2.2.6 on 2019-10-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191030_1317'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='url',
            name='unique_random_url',
        ),
        migrations.AddConstraint(
            model_name='url',
            constraint=models.UniqueConstraint(condition=models.Q(custom=False), fields=('long_url',), name='unique_random_url'),
        ),
    ]
